use std::error::Error;
use std::path::{Path, PathBuf};
use std::{env, fs};

use tidysql_config::{Config, Severity};
use tidysql_lints::metadata::{LINTS, LintMetadata, LintOption};

fn main() -> Result<(), Box<dyn Error>> {
    let mut args = env::args().skip(1);
    match args.next().as_deref() {
        Some("docs") => generate_docs(),
        _ => {
            eprintln!("Usage: cargo run -p xtask -- docs");
            std::process::exit(1);
        }
    }
}

fn generate_docs() -> Result<(), Box<dyn Error>> {
    let root = workspace_root()?;
    let docs_dir = root.join("docs/reference/lints");
    fs::create_dir_all(&docs_dir)?;

    let config = Config::default();
    let mut lint_pages = Vec::new();

    for lint in LINTS {
        let default_level = format_severity((lint.level)(&config));
        let content = render_lint_page(lint, default_level);
        let path = docs_dir.join(format!("{}.md", lint.code));
        write_file(&path, &content)?;
        lint_pages.push((lint, default_level));
    }

    let index_path = docs_dir.join("index.md");
    let index_content = render_index_page(&lint_pages);
    write_file(&index_path, &index_content)?;

    Ok(())
}

fn workspace_root() -> Result<PathBuf, Box<dyn Error>> {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let root = manifest
        .parent()
        .and_then(|path| path.parent())
        .ok_or("failed to resolve workspace root")?;
    Ok(root.to_path_buf())
}

fn write_file(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents)?;
    Ok(())
}

fn render_index_page(lints: &[(&LintMetadata, &str)]) -> String {
    let mut output = String::new();
    output.push_str("# Lint rules\n\n");
    output.push_str("<!-- Generated by xtask. Do not edit by hand. -->\n\n");
    output.push_str("This reference is generated from lint metadata in code.\n\n");
    output.push_str("## Configuration shape\n\n");
    output.push_str("- String: sets the lint level only. Example: `explicit_union = \"warn\"`.\n");
    output.push_str(
        "- Table: sets `level` and options. Example: `explicit_union = { level = \"warn\" }`.\n",
    );
    output.push_str(
        "- Array: supported by list-based lints like `disallow_names = [\"temp\", \"tmp\"]`.\n\n",
    );
    output.push_str("## Levels\n\n");
    output.push_str("- `allow`: disable the lint\n");
    output.push_str("- `warn`: report as warning\n");
    output.push_str("- `error`: report as error\n");
    output.push_str("- `info`: report as info\n");
    output.push_str("- `hint`: report as hint\n\n");
    output.push_str("## Lints\n\n");
    output.push_str("| Code | Category | Editor | Default | Fixable | Summary |\n");
    output.push_str("|------|----------|--------|---------|---------|---------|\n");

    for (lint, default_level) in lints {
        let fixable = if lint.fixable { "yes" } else { "no" };
        output.push_str(&format!(
            "| [`{code}`]({code}.md) | `{category}` | `{editor}` | `{default}` | {fixable} | \
             {summary} |\n",
            code = lint.code,
            category = lint.category.as_str(),
            editor = lint.editor_default.as_str(),
            default = default_level,
            fixable = fixable,
            summary = lint.summary
        ));
    }

    output.push('\n');
    output
}

fn render_lint_page(lint: &LintMetadata, default_level: &str) -> String {
    let mut output = String::new();
    output.push_str(&format!("# {}\n\n", lint.code));
    output.push_str("<!-- Generated by xtask. Do not edit by hand. -->\n\n");
    output.push_str(&format!("**Summary:** {}\n\n", lint.summary));
    output.push_str(&format!("**Category:** `{}`\n\n", lint.category.as_str()));
    output.push_str(&format!("**Editor default:** `{}`\n\n", lint.editor_default.as_str()));
    output.push_str(&format!("**Default level:** `{}`\n\n", default_level));
    output.push_str(&format!("**Fixable:** {}\n\n", yes_no(lint.fixable)));

    output.push_str("## Rationale\n\n");
    output.push_str(lint.rationale);
    output.push_str("\n\n");

    output.push_str("## Configuration\n\n");
    output.push_str("```toml\n");
    output.push_str(lint.config_example);
    output.push_str("\n```\n\n");

    render_options_table(&mut output, lint.options);

    if !lint.notes.is_empty() {
        output.push_str("## Notes\n\n");
        for note in lint.notes {
            output.push_str("- ");
            output.push_str(note);
            output.push('\n');
        }
        output.push('\n');
    }

    output.push_str("## Examples\n\n");
    output.push_str("**Anti-pattern:**\n\n");
    output.push_str("```sql\n");
    output.push_str(lint.anti_pattern);
    output.push_str("\n```\n\n");
    output.push_str("**Best practice:**\n\n");
    for best in lint.best_practices {
        output.push_str("```sql\n");
        output.push_str(best);
        output.push_str("\n```\n\n");
    }

    if !lint.dialects.is_empty() {
        output.push_str("## Dialect support\n\n");
        output.push_str("Supported dialects:\n\n");
        for dialect in lint.dialects {
            output.push_str("- ");
            output.push_str(dialect);
            output.push('\n');
        }
        output.push('\n');
    }

    output
}

fn render_options_table(output: &mut String, options: &[LintOption]) {
    output.push_str("### Options\n\n");
    if options.is_empty() {
        output.push_str("No options.\n\n");
        return;
    }

    output.push_str("| Option | Type | Default | Description |\n");
    output.push_str("|--------|------|---------|-------------|\n");
    for option in options {
        output.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} |\n",
            option.name, option.type_name, option.default_value, option.description
        ));
    }
    output.push('\n');
}

fn yes_no(value: bool) -> &'static str {
    if value { "yes" } else { "no" }
}

fn format_severity(severity: Severity) -> &'static str {
    match severity {
        Severity::Error => "error",
        Severity::Warn => "warn",
        Severity::Info => "info",
        Severity::Hint => "hint",
        Severity::Allow => "allow",
    }
}
